blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('detail/<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('tag/<str:tag>',views.TagView.as_view(),name='tag'),
]

project3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('markdownx/',include('markdownx.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

class Category(models.Model):
    name = models.CharField("category name",max_length=255)
    created_at = models.DateTimeField('datetime',default=timezone.now)

    def __str__(self):
        return self.name


class Tag(models.Model): # add
    name = models.CharField("tag",max_length=50)
    created_at = models.DateTimeField("作成日",auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    """Post articles"""
    title  = models.CharField('title',max_length=50)
    subtitle = models.CharField('subtitle',max_length=100,blank=True)
    # thumbnail = models.ImageField(upload_to='images/',blank=True)
    text = MarkdownxField('test_text')
    created_at = models.DateTimeField('datetime',default=timezone.now)
    category = models.ForeignKey(Category,verbose_name='category',on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag,blank=True,verbose_name='tag')
     # add
    def text_to_markdown(self):
        return markdownify(self.text)

    def get_previous_by_pk(self):
        """前のデータを取得する。"""
        return type(self).objects.filter(pk__lt=self.pk).last()

    def get_next_by_pk(self):
        """次のデータを取得する。"""
        return type(self).objects.filter(pk__gt=self.pk).first()



    def __str__(self):
        return self.title

blog/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from .models import Post,Category,Tag
from django.db.models import Q #　記事の内容を検索するためのパッケージ

class IndexView(generic.ListView):
    model = Post
    paginate_by = 2

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')#
        keyword = self.request.GET.get('keyword')#検索フォームからの入力内容を取得
        if keyword:
            #queryset = queryset.filter(title = keyword) 検索内容と記事名が完全に一致する場合
            queryset = queryset.filter( Q(title__icontains = keyword)|Q(text__icontains = keyword))
            # text_icontains...記事の内容を検索する時に使用
        return queryset

class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10
    def get_queryset(self):
        category = get_object_or_404(Category,pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        return queryset


class DetailView(generic.DetailView):
    model = Post


class TagView(generic.ListView):
    """タグのリンククリック"""

    def get_queryset(self):
        """タグで絞り込み"""
        tag_name = self.kwargs['tag']
        self.tag = Tag.objects.get(name=tag_name)
        queryset = Post.objects.order_by('-created_at').filter(tag=self.tag)
        return queryset

blog/templates/blog/base.html
<html>
<head>
  {% load static %}
  <title>Tokiのブログ</title>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Noto+Serif+SC:300" rel="stylesheet">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<style>
body{
  font-family: 'Noto Serif SC', serif;
}
a{
  color:gray;
}

.navbar{
  background-color: black;
}




</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'blog:index' %}">My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active ">
          <a class="nav-link text-center" href="{% url 'blog:index' %}">Home</a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link text-center" href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link text-center" href="https://twitter.com/tynk03179592?lang=ja">Twitter</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="jumbotron img-fluid center-block pc">
    <div class="col-auto text-white">
      <h2 class="display-5 title">Tokiのブログ</h2>
      <p class="lead">Python,Django,機械学習に関する情報を発信しています。</p>
      <p>This site provides information on Python, Django, and machine learning.</p>
      <p class="lead">
        <p>質問、感想などありましたら下のボタンからご連絡ください</p>
        <a href="mailto:aef6ji@gmail.com" class="btn btn-dark my-2">Email Me</a>
      </p>
    </div>
  </div>
  <div class="jumbotron img-fluid center-block sp">
    <div class="col-auto text-white">
      <h2 class="display-5 title">Tokiのブログ</h2>
      <p class="lead">Python,Django,機械学習に関する情報を発信しています。</p>
      <p>This site provides information on Python, Django, and machine learning.</p>
      <p class="lead">
        <p>質問、感想などありましたら下のボタンからご連絡ください</p>
        <a href="mailto:aef6ji@gmail.com" class="btn btn-dark my-2">Email Me</a>
      </p>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        {% block content %}
        {% endblock %}
      </div>

      <!-- sidebarのデザイン変更　ここから -->
      <div class="col-md-3">
        <form class="form-inline my-2 my-lg-0" method="GET" action = "{% url 'blog:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name ="keyword">
          <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="list-group list-group-flush mb-3">
          <li class="all-posts-title list-group-item">All categories</li>

          {% for category in category_list %}
          <li class="list-group-item"><a  href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
          {% endfor%}
        </ul>
        <ul class="list-group list-group-flush">
          <li class="list-group-item mt-5">All tags</li>
          {% for tag in tag_list %}
          <li class="list-group-item"><a href="{% url 'blog:tag' tag.name %}">{{ tag }}</a></li>
          {% endfor%}
        </ul>
      </div>
      <!--  ここまで -->
    </div>
    <div class="footer" >
      <p>2019©All rights reserved</p>
    </div>
         <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link  bg-dark text-white" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link bg-white text-dark" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link bg-dark text-white" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link bg-dark text-white" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}

  </ul>
</nav>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}


{% block content %}
<div class="card　mb-3">
    <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
<div class="card-body">
  <p>{{ post.created_at }},{{ post.category }}</p>
  {% comment %}
 {{ post.text |safe|linebreaksbr| urlize }}
 {% endcomment %}
 {% if post.text %}
 {{ post.text_to_markdown | safe }}
 {% endif %}
</div>
<a  class="btn btn-dark mb-5" href="{% url 'blog:index' %}">Back to Home</a>
</div>

{% with prev=post.get_previous_by_pk %}
  {% if prev %}
    <a href="{% url 'blog:detail' prev.pk %}">前の記事</a>
  {% endif %}
{% endwith %}


{% with next=post.get_next_by_pk %}
  {% if next %}
    <a href="{% url 'blog:detail' next.pk %}">次の記事</a>
  {% endif %}
{% endwith %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
   <h1><span style="font-weight:100;">All Posts</span></h1>
{% for post in post_list %}


<div class="post row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  {% comment %}
  <div class="col-auto d-none d-lg-block">
    <img class="thumbnail mt-2 ml-2 pr-2 pb-2 img-fluid" src='{{ post.thumbnail.url }}' >
  </div>
  {% endcomment %}
  <div class="col p-2 d-flex flex-column position-static">
    <strong class="d-inline-block mb-2 text-dark">{{ post.category }}</strong>
    <h3 class="mb-0">{{ post.title }}</h3>
    <div class="mb-1 text-muted">{{ post.created_at }}</div>
    <p class="card-text mb-auto">{{post.subtitle}}</p>
    <a href="{% url 'blog:detail' post.pk %}" class="btn btn-secondary" >Read More</a>
  </div>
</div>


{% endfor %}
{% include 'blog/page.html' %}
{% endblock %}